#!/usr/bin/env python3
"""Generate current release facts from repository data; --check detects drift."""

import argparse
import importlib.util
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_build():
    spec = importlib.util.spec_from_file_location("mcr_build", os.path.join(REPO, "build.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def facts():
    build = load_build()
    data = build.load_content()
    build.validate(data)
    entries = data["commands"]["entries"]
    default, receipts = build.compute_default_version(data)
    flags = {v: sum(len(tool.get("flags", [])) for tool in data["flags"][v].get("clis", {}).values())
             for v in build.VERSIONS}
    return {
        "version": build.APP_VERSION,
        "build_date": build.APP_BUILD_DATE,
        "curated_entries": len(entries),
        "guided_generators": sum("template" in entry for entry in entries),
        "static_entries": sum("template" not in entry for entry in entries),
        "tool_records": len(data["tools"]["tools"]),
        "default_rhel": default,
        "verified_receipts": receipts,
        "flag_rows": flags,
        "flag_rows_total": sum(flags.values()),
    }


def render_markdown(data):
    return """# Generated Release Facts

Do not edit this file by hand. Run `python3 tools/generate_release_facts.py`.

| Fact | Value |
|---|---:|
| Version | {version} |
| Build date | {build_date} |
| Curated entries | {curated_entries} |
| Guided generators | {guided_generators} |
| Static entries | {static_entries} |
| Tool records | {tool_records} |
| Derived default RHEL release | {default_rhel} |
| Verified receipts: RHEL 7 / 8 / 9 / 10 | {r7} / {r8} / {r9} / {r10} |
| Flag rows: RHEL 7 / 8 / 9 / 10 | {f7} / {f8} / {f9} / {f10} |
| Flag rows total | {flag_rows_total} |

The default release is derived by `build.compute_default_version`: the release
with the most real verification receipts wins, with a lower-version tie break.
""".format(r7=data["verified_receipts"]["7"], r8=data["verified_receipts"]["8"],
           r9=data["verified_receipts"]["9"], r10=data["verified_receipts"]["10"],
           f7=data["flag_rows"]["7"], f8=data["flag_rows"]["8"],
           f9=data["flag_rows"]["9"], f10=data["flag_rows"]["10"], **data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = facts()
    outputs = {
        os.path.join(REPO, "docs", "generated", "release-facts.json"):
            json.dumps(data, indent=2, sort_keys=True) + "\n",
        os.path.join(REPO, "docs", "generated", "RELEASE_FACTS.md"):
            render_markdown(data),
    }
    if args.check:
        stale = []
        for path, wanted in outputs.items():
            if not os.path.exists(path):
                stale.append(path)
                continue
            with open(path, encoding="utf-8") as handle:
                if handle.read() != wanted:
                    stale.append(path)
        if stale:
            for path in stale:
                print("STALE:", os.path.relpath(path, REPO), file=sys.stderr)
            return 1
        print("PASS: generated release facts are current")
        return 0
    os.makedirs(os.path.join(REPO, "docs", "generated"), exist_ok=True)
    for path, rendered in outputs.items():
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered)
        print("WROTE", os.path.relpath(path, REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
